import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menubar from "@/components/menubar";
import Sidepanel from "@/components/sidepanel";
import GroupsTable from "@/components/groupsTable";
import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Periscope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={inter.className}>
        <Menubar />
        <Header/>
        <GroupsTable />
        <Sidepanel />
        {children}
      </body>
    </html>
  );
}
